### PR TITLE
Mobility synchronization tool

### PR DESCRIPTION
**Pull request by jcte02**
@Piiit Here's the source code for the mobility synchronization tool.
It lives under the `infrastructure/utils/mobility-sync` path.
There are script for both a binary and a Docker release.

### CODE REVIEW

**Comment by Piiit** [comment]
@jcte02 could you please add a README either in the folder itself or a chapter in the main README to explain how to use this script and to explain why it exists? Thank you

**Comment by jcte02** [comment]
@Piiit Should I also integrate the synchronization tool into the docker-compose of the stack, or should it be run externally?

**Comment by Piiit** [comment]
I would integrate it there, so we have a single docker-compose.run.yml at the end to execute everything we need.

**Comment by jcte02** [comment]
The only problem I see is that Flyway is running from the Ontop container, so we have no guarantee that the tool will connect to a valid state of the database.
Maybe it's better if I merge this PR and #56 into a single PR?

**Comment by jcte02** [comment]
Also, how are we gonna handle two instances of the mobility synchronization tool running against the same database?
Because we now have a single database shared between test and production.
That also means that any test migration which runs through Flyway also impacts the production deployment, which is less than ideal.

**Comment by Piiit** [comment]
@jcte02 We could either test everything locally and then only push if things work, seeing that we have only a few users, we could manually fix things if something goes wrong... not ideal! You are right about that.

Or, have a test db with only a subset of data synced to test schema updates beforehand. Timeouts or other server constraints would not be tested though, just the business logic behind. Good enough I guess.

I just want to avoid manual work for updates...

**Pull request merged**
