### PR TITLE
Remove Flyway and migrate to new database

### PR DESCRIPTION
**Pull request by jcte02**
This PR removes Flyway and all its accessory configuration in favor of the new VKG database, which is maintained via external synchronization scripts instead of logical replication.

The documentation has been updated to remove any mention about logical replication.

Before deploying the new configuration it will be necessary to update the credentials for `'it.bz.opendatahub.sparql.db.vkg.password.readonly'` with the one for the user `ontopicreadonly` in the new database.

### CODE REVIEW

**Comment by Piiit** [comment]
@jcte02 Why do you remove the flyway scripts? We should probably just adapt them and remove the logical replication part. Or does your sync script also create schemas if they are missing?

**Comment by Piiit** [comment]
@jcte02 BTW, I still miss the sync script, do we want to add it here or should I create another repository for you?

**Comment by jcte02** [comment]
@Piiit No, the new tooling does not manage the schema. It however expects to work with a known schema, in particular with the reference constraints between the tables.
At the moment, I have the SQL script I used to create the mobility schema in the VKG database committed alongside the new tool. If you want to, I could try to fit it in with the existing Flyway tooling, but the idea was to stop running Flyway alongside Ontop, since it's not really needed anymore.
I don't expect the mobility schema to change, and if indeed it does, it's more of a one-time manual operation to update it than something that should happen automatically. Because remember, with a schema change the mobility synchronization tool also needs to be updated.
I personally see the database as an external dependency of the synchronization tool, and as such it should be managed externally, which could be manually through Flyway.
I originally developed the mobility synchronization tool against this repository in a separate branch, so for convenience I think it should live here in this repository. I will open a separate PR for that though.

**Comment by Piiit** [comment]
@jcte02 
Our workflow for deployment should not require any manual steps. That is, we should in the future just push to the repository and automatically deploy (or update) anything needed to have the VKG running.

This includes also schema updates. For that we always used Flyway. You are right though, that the schema definition does not belong to the update script alone, but to the whole Ontop installation. I would therefore keep Flyway and just remove unnecessary parts from that.

A future PR could then contain the schema updates as flyway sql scripts, the new updated sync tool and new mappings all in one PR. So we just merge that PR and are done, hopefully. If the SQL updates fail or go in timeout, we can still do it manually with those scripts, but have a versioning of that schema in place.

As for the script it is fine to have it inside this `infrastructure/utils` folder

**Pull request merged**
