### PR TITLE
Spatial indexes and geometry literals moved to companion classes in the mapping

### PR DESCRIPTION
**Pull request by bcogrel**
This PR introduces:
  1. Spatial indexes to speed up geospatial queries and bypass a bug in Ontop 4.1.0 .
  2. The geo:asWKT properties are now used by the schema:GeoCoordinates companion classes, not by classes like schema:LodgingBusiness directly anymore. 
  3. A small bugfix regarding the Nginx configuration affecting the dev Docker-compose settings.

Note that the second point may break existing queries, such as the one used by the Web component. Shall we simply update the latter query or shall we keep binding the geo:asWKT property to the main class and treat it as deprecated?

### CODE REVIEW

**Comment by Piiit** [comment]
@bcogrel Thanks for the update. I think at this point with only a few users we can still afford to have incompatibilities between versions... but that should be kept to a minimum. So please make also a PR for the web component, and all no-longer working queries. Could you also please add a query that works only for logged-in users, to have a fast test of authentication?

Please just push to this PR, and when you are done remove the WIP prefix... thx

**Comment by bcogrel** [comment]
Hi, I have updated the example queries for the Web component (https://github.com/noi-techpark/webcomp-kg/pull/6).

@ghxiao, could you please add a SPARQL query returning results only to authenticated users to the portal file?

Best,
Benjamin

**Comment by Piiit** [comment]
@bcogrel Thanks, please ping me, when this PR is ready to be integrated...

**Comment by bcogrel** [comment]
Hi @Piiit , sorry for the delay, this PR should now be ready.

Additional changes :
  - the query for testing the access control restrictions has been added (Mobility -> Non-public weather observations) 
  -  Covid-19 entries have been removed (query, mapping, ontology). It should close  #41
  - We interconnected the municipality dataset with lodging businesses. Needed for querying on a per municipality manner in a robust way (the postal code is not reliable).

Best,
Benjamin

**Comment by Piiit** [comment]
@bcogrel Thx

**Pull request merged**
